# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40e25fef810c73d85afeb2da87dda7925f0932dcd35f7712cb407e487dd8f63d5149e0a7036ee7f1725d262ae0983037a581d54610b1d574c173400e4d10ec2b

test:
  secret_key_base: ea6dd69dc7a94a72fecffdac085cab962df99b3d99a3f9f1758a974526b0d2a5d1055471d13d1282b37779ba5db762f15433fd7e88fe197d507be81a4a52aac5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
